name: Docker

on:
  push:
    branches:
      - main
    paths:
      - 'VERSION'
  pull_request:
    branches:
      - main
    paths:
      - 'VERSION'
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Test
        run: go test -v ./...

      - name: Build
        run: go build -v ./...

      - name: Build and push image
        run: |
          tmpName="image-$RANDOM"
          docker build --tag $tmpName .
          IMAGE_ID=${{ secrets.DOCKERHUB_USERNAME }}/tidbyt-proxy
          VERSION=$(cat VERSION)

          docker tag $tmpName $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
      